### ISSUE TITLE
What else do I need?

### ISSUE THREAD

**Issue by MonkeyMack** [RainFemboy/murrtube-downloader#3]
This happens when I try it:
Traceback (most recent call last):
  File "C:\Temp\murrtube-dl.py", line 61, in <module>
    download_video(url)
  File "C:\Temp\murrtube-dl.py", line 32, in download_video
    subprocess.run(ffmpeg_command)
  File "C:\Users\Monkey\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Monkey\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Monkey\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by zeozeozeo** [comment]
you need to install ffmpeg

**Comment by RainFemboy** [comment]
> you need to install ffmpeg

This is correct, The issue seems to be you are missing ffmpeg.
